# Generated by Django 6.0.6 on 2026-07-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacterium', models.CharField(db_index=True, max_length=255)),
                ('raw_score', models.FloatField()),
                ('sequence', models.TextField()),
                ('annotation', models.TextField()),
                ('iso_calibrated_probability', models.FloatField()),
                ('bacterium_name_formatted', models.CharField(db_index=True, max_length=255)),
                ('assembly', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(db_index=True, max_length=50)),
                ('strain', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
