version: "3.9"

services:

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432" # Secured to localhost

  flask:
    build:
      context: ./flask_api
    container_name: prediction_service
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "127.0.0.1:5001:5000" # Exposes container 5000 as host 5001 explicitly on localhost

  django:
    build:
      context: ./django
    container_name: django_frontend
    restart: always
    depends_on:
      - db
      - flask
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000" # Exposes container 8000 as host 8000 explicitly on localhost
    volumes:
      - ./django:/app
      - ./data:/data

volumes:
  postgres_data: